"""Entity 레이어 도메인 상수."""

USER_ID_MAX_LENGTH: int = 64
DISPLAY_NAME_MAX_LENGTH: int = 100
USER_ID_MIN_LENGTH: int = 1
DISPLAY_NAME_MIN_LENGTH: int = 1

GRID_SIZE: int = 4
MIN_CELL_VALUE: int = 1
MAX_CELL_VALUE: int = 16
EMPTY_CELL_VALUE: int = 0
REQUIRED_EMPTY_CELL_COUNT: int = 2
MAGIC_CONSTANT: int = 34
SOLUTION_LENGTH: int = 6
